database:
  schema: ${DB_SCHEMA:book_store}
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:3306}
  username: ${DB_USER}
  password: ${DB_PASS}

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

spring:
  cache:
    type: redis

  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.schema}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${database.username}
    password: ${database.password}

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  redis:
    host: ${redis.host}
    port: ${redis.port}

logging:
  level:
    org.springframework.cache: trace
    org.springframework.web: trace
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
